name: presentation
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.1
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  icons_plus: ^5.0.0
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  flutter_widget_from_html: ^0.15.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  super_banners: ^0.0.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  introduction_screen: ^3.1.14
  animated_splash_screen: ^1.3.0
  animated_toggle_switch: ^0.8.2
  flutter_svg: ^2.0.10+1

  core:
    path: ../core
  domain:
    path: ../domain
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true # Add this line
  uses-material-design: true
