name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  intl: ^0.19.0
  icons_plus: ^5.0.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  elegant_notification: ^2.2.1
  page_animation_transition: ^1.0.0
  animations: ^2.0.11


  domain:
    path: ../domain
  presentation:
    path: ../presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true # Add this line
  uses-material-design: true
