// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FxabMf4lAoUzdaeBzqBvboZmrrPMcBk',
    appId: '1:186024455231:web:ec22f9d0fb142bddc65c8a',
    messagingSenderId: '186024455231',
    projectId: 'el3b-355b4',
    authDomain: 'el3b-355b4.firebaseapp.com',
    storageBucket: 'el3b-355b4.appspot.com',
    measurementId: 'G-PLJ5XNWDVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIE5Lb2X4eHQhME5ukxD1EI6VPHnGPEGM',
    appId: '1:186024455231:android:e30ab6fef161653ec65c8a',
    messagingSenderId: '186024455231',
    projectId: 'el3b-355b4',
    storageBucket: 'el3b-355b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKzBpjjjwqblpnoN8bBmbio7TBiFenMY',
    appId: '1:186024455231:ios:db17692010737821c65c8a',
    messagingSenderId: '186024455231',
    projectId: 'el3b-355b4',
    storageBucket: 'el3b-355b4.appspot.com',
    iosClientId: '186024455231-3gt89j4vekl1mcrlenp8d2qotdi47fns.apps.googleusercontent.com',
    iosBundleId: 'com.example.elab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKzBpjjjwqblpnoN8bBmbio7TBiFenMY',
    appId: '1:186024455231:ios:cf5441000c7cfab1c65c8a',
    messagingSenderId: '186024455231',
    projectId: 'el3b-355b4',
    storageBucket: 'el3b-355b4.appspot.com',
    iosClientId: '186024455231-cajtrk9nllfghgncu9utv36idolqujof.apps.googleusercontent.com',
    iosBundleId: 'com.example.elab.RunnerTests',
  );
}
